[package]
name = "ckv"
version = "0.1.0"
edition = "2021"

[dependencies]
bloom = "0.3.2"
crc = "3.2.1"
crossbeam-skiplist = "0.1.3"
memmap2 = "0.9.5"
prost = "0.13.3"
rand = "0.8.5"
tokio = {version = "1.41.0", features = ["full"]}
[build-dependencies]
prost-build = "0.13.3"
